name: build and publish docker image

on:
  schedule:
    - cron: '0 4 * * *' # everyday at 4am
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up buildx
        uses: docker/setup-buildx-action@v1
          
      - name: login to docker hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: login to github container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
          
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          # allow: network.host
          push: true
          tags: |
            dotwee/adb-mqtt-bridge:latest
            ghcr.io/dotwee/adb-mqtt-bridge:latest
 
